export const data = [
    {
        _id: '1',
        name: 'Apple iPhone 7',
        category: 'phone',
        image: 'https://m.media-amazon.com/images/I/31+rHqWgOrL._AC_UY327_FMwebp_QL65_.jpg',
        price: 299,
        brand: 'apple',
        rating: 4.6,
        stock: 8,
    },
    {
        _id: '2',
        name: 'Canon Pixma TR150 Wireless Mobile Printer',
        category: 'Printer',
        image: 'https://m.media-amazon.com/images/I/81utqYDcRTL._AC_UY327_FMwebp_QL65_.jpg',
        price: 199,
        brand: 'Cannon',
        rating: 4.2,
        stock: 4,
    },
    {
        _id: '3',
        name: 'Samsung SSD 860 EVO',
        category: 'SSD',
        image: 'https://m.media-amazon.com/images/I/91JA5-hAnoL._AC_UY327_FMwebp_QL65_.jpg',
        price: 108,
        brand: 'Samsung',
        rating: 4.9,
        stock: 12,
    },
    {
        _id: '4',
        name: 'Apple iPhone X',
        category: 'Phone',
        image: 'https://m.media-amazon.com/images/I/81SSw14XZHL._AC_UY327_FMwebp_QL65_.jpg',
        price: 354,
        brand: 'Apple',
        rating: 4.2,
        stock: 12,
    },
    {
        _id: '5',
        name: 'BenQ 24 Inch IPS Monitor',
        category: 'TV',
        image: 'https://m.media-amazon.com/images/I/712ZOa8Ze2L._AC_UY327_FMwebp_QL65_.jpg',
        price: 119,
        brand: 'BenQ',
        rating: 4.7,
        stock: 10,
    },
    {
        _id: '6',
        name: 'Schwinn GTX Comfort',
        category: 'Schwinn',
        image: 'https://m.media-amazon.com/images/I/91lZHmWsEML._AC_UL480_FMwebp_QL65_.jpg',
        price: 597,
        brand: 'Samsung',
        rating: 3.2,
        stock: 5,
    },
]